# This file is generated by androgenizer for:
# [x] NDK
# [ ] system

LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE:=libimageio

LOCAL_SRC_FILES := \
	src/imageio.c

LOCAL_LDLIBS := -lpng -lz

#LOCAL_STATIC_LIBRARIES:=\
	#libpng

LOCAL_CFLAGS := \
	-std=c99 \
	-Wall \
	-O3

LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)
